#!/usr/bin/env bash
# Script to do a lot

echo "$$" >> /var/run/myscript.pid

terminate() {
    rm /var/run/myscript.pid
    exit
}

while true
do
    echo "To infinity and beyond"
    sleep 2
    trap 'echo "I hate the kill command" && terminator' SIGTERM
    trap 'echo "Y U no love me?!"' SIGINT
    trap 'terminator' SIGQUITgit
done