#!/usr/bin/env bash

x=0

while [ $x -le 9 ]
do
    if [ $x -eq 3 ]
    then
        echo "bad luck"
    elif [ $x -eq 7 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi

    (( x++ ))
done