#!/usr/bin/env bash

hour=0
minutes=1

while [ $hour -le 12 ]
do
    echo "Hour: $hour"
    while [ $minutes -le 59 ]
    do
        echo "$minutes"
        (( minutes++ ))
    done

    minutes=1
    (( hour++ ))
done